export const SERVICE_CATEGORIES: Record<string, string[]> = {
  'Private Security and Guarding Services': [
    'Guard Male',
    'Guard Female',
  ],
  'Housekeeping, Cleaning & Hospitality': [
    'Care Takeer',
    'Cleaning Staff for Home & Office',
    'Male Peon for office and home',
    'Female Peon for office and home',
    'Nurses and Wardboys',
    'Gardner for office and home',
    'Plumber',
    'Carpenters',
    'Electrician',
    'AC repair and servicing',
    'Penter',
    'Washroom cleaning',
    'Pest control',
  ],
  'Event Management': [
    'Marriage',
    'Birthday',
    'Anniversary',
    'Office Celebration',
    'Public Events & Gathering',
    'VIP Programs',
    'competitive Arrangements',
  ],
  'Cultural Program, Drama & Dance': [
    'Stage Drama Show',
    'Stage Dance Show',
    'Sports Programs',
    'School Cultural Programs',
    'College Cultural Programs',
    'Drama & Dance Competition',
  ],
  'Skill Development, Health & AI Training': [
    'AI Trainer',
    'Technical Trainer',
    'School Teacher',
  ],
  'Women Empowerment & Social Initiatives': [
    'Manager',
    'Training Staff',
    'Back office Staff',
    'Mobilizer',
    'Sanitation Staff',
  ],
  'Job Placement & Recruitment Consultancy': [
    'Private Office',
    'Technical Jobs',
    'Hospitality Jobs',
    'Administrative Jobs',
    'None Technical Jobs',
    'Sales/Marketing',
    'Finance',
    'Teachers/Professor',
  ],
  'Skilled & Unskilled Manpower Supply': [
    'Mason',
    'Labour',
    'Carpenters',
    'Plumbers',
    'Painters',
    'Gardener',
    'AC Repair staff',
    'Guard Male/Female',
    'Training Staff',
    'Back Office Staff',
    'Others',
  ],
  'Tour, Travel & Transportation Services': [
    'Taxi Services',
    'Bus Services',
    'Movers , Packers & Transportation Services',
    'Office Tour Packages',
    'Family Tour Packages',
  ],
  'Courier, Corgo & Logistics': [
    'E-Commerce Services(B to B & B to C)',
    'Parcel and Documents Services',
    'Cargo Services',
    'International Courier Services',
  ],
  'Government and Private Tenders': [
    'All types of goods,food and material supply',
  ],
};
